service:
  name: reason-proxy

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1

functions:
  proxy:
    memorySize: 256
    timeout: 29
    handler: proxy.handler
    events:
      - http:
          method: get
          path: /proxy
