// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var AwsLambda = require("@ahrefs/bs-aws-lambda/src/awsLambda.bs.js");

function handler(_event, _context, cb) {
  Curry._2(cb, null, AwsLambda.APIGatewayProxy[/* result */3](undefined, /* `Plain */[
            -675583510,
            "Hello from reason code!"
          ], 200, /* () */0));
  return Promise.resolve(/* () */0);
}

exports.handler = handler;
/* No side effect */
